server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

loadbalancer.client.name=movie-service